"""added info column to work table

Revision ID: 243735b65080
Revises: cf66d0d8eba9
Create Date: 2023-09-24 19:26:51.670429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243735b65080'
down_revision = 'cf66d0d8eba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
