"""added completed_at column with setters for time stamping

Revision ID: e2a75a9dc4a8
Revises: 3b058acd360e
Create Date: 2023-09-25 19:20:52.706948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a75a9dc4a8'
down_revision = '3b058acd360e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
